import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import PageLayout from "components/layouts/pages/PageLayout";
import MainHeader from "components/layouts/headers/MainHeader";
import MainBanner from "components/layouts/banner/MainBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"en"}>
      <body>
        <PageLayout>
          <MainBanner>
            <MainHeader />
          </MainBanner>
          {children}
        </PageLayout>
      </body>
    </html>
  );
}
